site_url: http://10.2.2.10
env: dev

database:
  driver: mysql
  host: localhost
  database: olimp_db
  username: root
  password: root
  port: 3306
  charset: utf8
  collation: utf8_unicode_ci
  prefix: oi_

session:
  cookie_lifetime: 0

datetime:
  timezone: Europe/Kiev

template:
  path: /template
  extensions: /helpers/classes/twig

migration:
  path: /migrations
  table: phinxlog